### ISSUE TITLE
Integration Framework for all Jobs and Projects Default

### ISSUE THREAD

**Issue by nixmomo** [jszaszvari/rundeck-rocketchat-notifier#1]
Hi,
can you explain more about the Framework integration?
I have set the options in /etc/rundeck/framework.properties
framework.plugin.Notification.RocketChatNotification.webhook_url=my-url
framework.plugin.Notification.RocketChatNotification.room=#my-channel

but it don't send notifications to my Rocket Chat

**Comment by jszaszvari** [comment]
Apologies, this was mistakenly left in the README.

It was not included in the initial release as i had issues with it. 

I'm working on getting it going so I expect to have another release within the next 30 days with more info and instructions on how to configure it. 

I've removed the mention of it from the README for the time being.

Very sorry!

**Comment by theduusK** [comment]
Hey @jszaszvari 

Can you already estimate when the next release with a possible project-wide configuration is available?
We're very interested in this feature as we don't want to configure 25 jobs in each of our 8 projects.
If you have a release during the next 2 weeks, we would wait for it instead of configuring each job :)

BR,
Patrick
